/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Lab_3;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author ToanNM_PC09504
 */
public class Bai_1 extends javax.swing.JFrame {

    JFileChooser fileChooser = new JFileChooser();

    /**
     * Creates new form Bai_1
     */
    public Bai_1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GroupColor = new javax.swing.ButtonGroup();
        jToolBar1 = new javax.swing.JToolBar();
        btnNew = new javax.swing.JButton();
        btnAbout = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtVanBan = new javax.swing.JTextArea();
        pnlNen = new javax.swing.JPanel();
        txtFpoly_java2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mnuFile_New = new javax.swing.JMenuItem();
        mnuFile_Open = new javax.swing.JMenuItem();
        mnuFile_Save = new javax.swing.JMenuItem();
        mnuColor = new javax.swing.JMenu();
        mnuColor_rdoRed = new javax.swing.JRadioButtonMenuItem();
        mnuColor_rdoGreen = new javax.swing.JRadioButtonMenuItem();
        mnuColor_rdoBlue = new javax.swing.JRadioButtonMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuColor_TextColor = new javax.swing.JRadioButtonMenuItem();
        mnuSystem = new javax.swing.JMenu();
        mnuSystem_About = new javax.swing.JMenuItem();
        mnuSystem_Exit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Java 2");

        jToolBar1.setRollover(true);

        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Notes.png"))); // NOI18N
        btnNew.setFocusable(false);
        btnNew.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNew.setMargin(new java.awt.Insets(20, 25, 20, 25));
        btnNew.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNew);

        btnAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/User.png"))); // NOI18N
        btnAbout.setFocusable(false);
        btnAbout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAbout.setMargin(new java.awt.Insets(20, 25, 20, 25));
        btnAbout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAbout);

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Exit.png"))); // NOI18N
        btnExit.setFocusable(false);
        btnExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExit.setMargin(new java.awt.Insets(20, 25, 20, 25));
        btnExit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jToolBar1.add(btnExit);

        txtVanBan.setColumns(20);
        txtVanBan.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        txtVanBan.setRows(5);
        txtVanBan.setText("Uống Nước Nhớ Nguồn\n\nCông cha như núi thái sơn\nNghĩa mẹ như nước trong nguồn chảy ra\nMột lòng thờ mẹ kính cha\nCho tròn chữ hiếu mới là đạo con\n\n........\n");
        jScrollPane1.setViewportView(txtVanBan);

        pnlNen.setBackground(new java.awt.Color(0, 255, 0));

        txtFpoly_java2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        txtFpoly_java2.setForeground(new java.awt.Color(255, 0, 255));
        txtFpoly_java2.setText("Fploy - Java 2");

        javax.swing.GroupLayout pnlNenLayout = new javax.swing.GroupLayout(pnlNen);
        pnlNen.setLayout(pnlNenLayout);
        pnlNenLayout.setHorizontalGroup(
            pnlNenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNenLayout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addComponent(txtFpoly_java2)
                .addContainerGap(273, Short.MAX_VALUE))
        );
        pnlNenLayout.setVerticalGroup(
            pnlNenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtFpoly_java2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenuBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 153, 153), null, null));

        mnuFile.setText("File");
        mnuFile.setMargin(new java.awt.Insets(5, 15, 5, 15));
        mnuFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuFileActionPerformed(evt);
            }
        });

        mnuFile_New.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        mnuFile_New.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Notes.png"))); // NOI18N
        mnuFile_New.setText("New");
        mnuFile_New.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuFile_NewActionPerformed(evt);
            }
        });
        mnuFile.add(mnuFile_New);

        mnuFile_Open.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        mnuFile_Open.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Open folder.png"))); // NOI18N
        mnuFile_Open.setText("Open");
        mnuFile_Open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuFile_OpenActionPerformed(evt);
            }
        });
        mnuFile.add(mnuFile_Open);

        mnuFile_Save.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        mnuFile_Save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Save.png"))); // NOI18N
        mnuFile_Save.setText("Save");
        mnuFile_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuFile_SaveActionPerformed(evt);
            }
        });
        mnuFile.add(mnuFile_Save);

        jMenuBar1.add(mnuFile);

        mnuColor.setText("Color");
        mnuColor.setMargin(new java.awt.Insets(5, 15, 5, 15));

        GroupColor.add(mnuColor_rdoRed);
        mnuColor_rdoRed.setSelected(true);
        mnuColor_rdoRed.setText("Red");
        mnuColor_rdoRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuColor_rdoRedActionPerformed(evt);
            }
        });
        mnuColor.add(mnuColor_rdoRed);

        GroupColor.add(mnuColor_rdoGreen);
        mnuColor_rdoGreen.setText("Green");
        mnuColor_rdoGreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuColor_rdoGreenActionPerformed(evt);
            }
        });
        mnuColor.add(mnuColor_rdoGreen);

        GroupColor.add(mnuColor_rdoBlue);
        mnuColor_rdoBlue.setText("Blue");
        mnuColor_rdoBlue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuColor_rdoBlueActionPerformed(evt);
            }
        });
        mnuColor.add(mnuColor_rdoBlue);
        mnuColor.add(jSeparator1);

        mnuColor_TextColor.setSelected(true);
        mnuColor_TextColor.setText("Text Color");
        mnuColor_TextColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuColor_TextColorActionPerformed(evt);
            }
        });
        mnuColor.add(mnuColor_TextColor);

        jMenuBar1.add(mnuColor);

        mnuSystem.setText("System");
        mnuSystem.setMargin(new java.awt.Insets(5, 15, 5, 15));

        mnuSystem_About.setText("About us");
        mnuSystem_About.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSystem_AboutActionPerformed(evt);
            }
        });
        mnuSystem.add(mnuSystem_About);

        mnuSystem_Exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        mnuSystem_Exit.setText("Exit");
        mnuSystem_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSystem_ExitActionPerformed(evt);
            }
        });
        mnuSystem.add(mnuSystem_Exit);

        jMenuBar1.add(mnuSystem);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addComponent(pnlNen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlNen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void openFile() {
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            try {
                BufferedReader reader = new BufferedReader(new FileReader(file));
                txtVanBan.read(reader, null);
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }

    public void saveFile() {
        int result = fileChooser.showSaveDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File fname = fileChooser.getSelectedFile();
            try {
                PrintWriter pw = new PrintWriter(fname);
                pw.println(txtVanBan.getText());
                pw.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }
    private void mnuFile_OpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuFile_OpenActionPerformed
        openFile();
    }//GEN-LAST:event_mnuFile_OpenActionPerformed

    private void mnuColor_rdoGreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuColor_rdoGreenActionPerformed
        pnlNen.setBackground(Color.GREEN);
    }//GEN-LAST:event_mnuColor_rdoGreenActionPerformed

    private void mnuColor_TextColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuColor_TextColorActionPerformed
        Color color = JColorChooser.showDialog(this, "Chọn Màu Chữ", Color.BLACK);
        txtVanBan.setForeground(color);
    }//GEN-LAST:event_mnuColor_TextColorActionPerformed

    private void mnuSystem_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSystem_ExitActionPerformed
        int kq = JOptionPane.showConfirmDialog(this, "Bạn Muốn Lưu Không");
        if(kq == JOptionPane.YES_OPTION){
            saveFile();
            System.exit(0);
        }else if (kq == JOptionPane.NO_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_mnuSystem_ExitActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        int kq = JOptionPane.showConfirmDialog(this, "Bạn Muốn Lưu Không");
        if(kq == JOptionPane.YES_OPTION){
            saveFile();
            txtVanBan.setText("");
        }else if (kq == JOptionPane.NO_OPTION){
            txtVanBan.setText("");
        }
    }//GEN-LAST:event_btnNewActionPerformed

    private void mnuFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuFileActionPerformed

    }//GEN-LAST:event_mnuFileActionPerformed

    private void mnuFile_NewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuFile_NewActionPerformed
        btnNewActionPerformed(evt);
    }//GEN-LAST:event_mnuFile_NewActionPerformed

    private void mnuFile_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuFile_SaveActionPerformed
        saveFile();
    }//GEN-LAST:event_mnuFile_SaveActionPerformed

    private void mnuColor_rdoRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuColor_rdoRedActionPerformed
        pnlNen.setBackground(Color.RED);
    }//GEN-LAST:event_mnuColor_rdoRedActionPerformed

    private void mnuColor_rdoBlueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuColor_rdoBlueActionPerformed
        pnlNen.setBackground(Color.BLUE);
    }//GEN-LAST:event_mnuColor_rdoBlueActionPerformed

    private void mnuSystem_AboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSystem_AboutActionPerformed
        JOptionPane.showMessageDialog(this, "PHẦN MỀM QUẢN LÝ\nTác giả: Nguyễn Mộc Toàn\nPhiên Bản: 1.0.0\nNgày tạo: 23/07/2024\nNgày cập nhật: 23/07/2024", "Giới Thiệu", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_mnuSystem_AboutActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        mnuSystem_ExitActionPerformed(evt);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutActionPerformed
        mnuSystem_AboutActionPerformed(evt);
    }//GEN-LAST:event_btnAboutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bai_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bai_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bai_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bai_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bai_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GroupColor;
    private javax.swing.JButton btnAbout;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnNew;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenu mnuColor;
    private javax.swing.JRadioButtonMenuItem mnuColor_TextColor;
    private javax.swing.JRadioButtonMenuItem mnuColor_rdoBlue;
    private javax.swing.JRadioButtonMenuItem mnuColor_rdoGreen;
    private javax.swing.JRadioButtonMenuItem mnuColor_rdoRed;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenuItem mnuFile_New;
    private javax.swing.JMenuItem mnuFile_Open;
    private javax.swing.JMenuItem mnuFile_Save;
    private javax.swing.JMenu mnuSystem;
    private javax.swing.JMenuItem mnuSystem_About;
    private javax.swing.JMenuItem mnuSystem_Exit;
    private javax.swing.JPanel pnlNen;
    private javax.swing.JLabel txtFpoly_java2;
    private javax.swing.JTextArea txtVanBan;
    // End of variables declaration//GEN-END:variables
}
