/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Lab_5;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ToanNM_PC09504
 */
public class Bai_2 extends javax.swing.JFrame {

    DefaultTableModel model = new DefaultTableModel();
    DefaultComboBoxModel model_box = new DefaultComboBoxModel();
    Connection ketNoi;

    /**
     * Creates new form Bai_2
     */
    public Bai_2() throws ClassNotFoundException, SQLException {
        initComponents();
        DatTenCot();
        DoDuLieuLenBang();
        DoDuLieuLenComboBox();
        btnCapNhat.setEnabled(false);
        btnXoa.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBang = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMaSp = new javax.swing.JTextField();
        txtTenSp = new javax.swing.JTextField();
        txtDonGia = new javax.swing.JTextField();
        txtSoLuong = new javax.swing.JTextField();
        cboLoaiSanPham = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        btnStart = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnEnd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh Sách", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        tblBang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBang);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông Tin", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        jLabel1.setText("Mã SP :");

        jLabel2.setText("Tên SP :");

        jLabel3.setText("Đơn Giá :");

        jLabel4.setText("Số Lượng :");

        jLabel5.setText("Loại Sản Phẩm :");

        cboLoaiSanPham.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboLoaiSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboLoaiSanPhamActionPerformed(evt);
            }
        });

        jPanel3.setLayout(new java.awt.GridLayout(2, 4, 25, 25));

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        jPanel3.add(btnThem);

        btnCapNhat.setText("Cập Nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });
        jPanel3.add(btnCapNhat);

        btnXoa.setText("Xoá");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        jPanel3.add(btnXoa);

        btnLamMoi.setText("Làm Mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });
        jPanel3.add(btnLamMoi);

        btnStart.setText("|<");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });
        jPanel3.add(btnStart);

        btnBack.setText("<<");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel3.add(btnBack);

        btnNext.setText(">>");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        jPanel3.add(btnNext);

        btnEnd.setText(">|");
        btnEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEndActionPerformed(evt);
            }
        });
        jPanel3.add(btnEnd);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(31, 31, 31))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(40, 40, 40))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(44, 44, 44))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(47, 47, 47)))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cboLoaiSanPham, 0, 202, Short.MAX_VALUE)
                                    .addComponent(txtSoLuong)
                                    .addComponent(txtMaSp))
                                .addComponent(txtDonGia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtTenSp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMaSp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTenSp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cboLoaiSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cboLoaiSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboLoaiSanPhamActionPerformed

    }//GEN-LAST:event_cboLoaiSanPhamActionPerformed

    private void tblBangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBangMouseClicked
        btnCapNhat.setEnabled(true);
        btnXoa.setEnabled(true);
        DanhSach();
    }//GEN-LAST:event_tblBangMouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        try {
            if (check()) {
                if (tblBang.getRowCount() > 0) {
                    for (int i = 0; i < tblBang.getRowCount(); i++) {
                        if (txtMaSp.getText().equalsIgnoreCase(tblBang.getValueAt(i, 0).toString())) {
                            JOptionPane.showMessageDialog(this, "Trùng Mã Sản Phẩm");
                            return;
                        }
                    }
                    KetNoiCSDL();
                    DecimalFormat df = new DecimalFormat("###,###");
                    String sql = "INSERT INTO SanPham VALUES(?,?,?,?,?)";
                    PreparedStatement cauLenh = ketNoi.prepareStatement(sql);
                    cauLenh.setString(1, txtMaSp.getText());
                    cauLenh.setString(2, txtTenSp.getText());
                    cauLenh.setString(3, txtDonGia.getText());
                    cauLenh.setInt(4, Integer.parseInt(txtSoLuong.getText()));
                    for (int i = 1; i <= cboLoaiSanPham.getWidth(); i++) {
                        if ((cboLoaiSanPham.getSelectedIndex() + 1) == i) {
                            cauLenh.setInt(5, i);
                        }
                    }
                    cauLenh.executeUpdate();
                    ketNoi.close();
                    DoDuLieuLenBang();
                }
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Lab_5.Bai_2.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Lab_5.Bai_2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        try {
            if (tblBang.getSelectedRow() == -1) {
                JOptionPane.showMessageDialog(this, "Bạn Chưa Chọn Dòng để Cập Nhật");
            } else {
                KetNoiCSDL();
                DecimalFormat df = new DecimalFormat("###,###");
                String sql = "UPDATE SanPham SET tenSP = ?,donGia = ?,soLuong = ?, MALOAI = ? WHERE maSanPham = ?";
                PreparedStatement cauLenh = ketNoi.prepareStatement(sql);
                cauLenh.setString(1, txtTenSp.getText());
                cauLenh.setString(2, txtDonGia.getText());
                cauLenh.setInt(3, Integer.parseInt(txtSoLuong.getText()));
                for (int i = 1; i <= cboLoaiSanPham.getWidth(); i++) {
                    if ((cboLoaiSanPham.getSelectedIndex() + 1) == i) {
                        cauLenh.setInt(4, i);
                    }
                }
                cauLenh.setString(5, txtMaSp.getText());
                cauLenh.executeUpdate();
                ketNoi.close();
                DoDuLieuLenBang();
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Lab_5.Bai_2.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Lab_5.Bai_2.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        try {
            if (tblBang.getSelectedRow() == -1) {
                JOptionPane.showMessageDialog(this, "Bạn Chưa Chọn Dòng để xoá");
            } else {
                KetNoiCSDL();
                String sql = "DELETE SanPham WHERE maSanPham = ?";
                PreparedStatement cauLenh = ketNoi.prepareStatement(sql);
                cauLenh.setString(1, txtMaSp.getText());
                // Ban chac chan muon xoa khong
                int kq = JOptionPane.showConfirmDialog(this, "Bạn Chắc Chắn Xoá");
                if (kq == JOptionPane.YES_OPTION) {
                    cauLenh.executeUpdate();
                    ketNoi.close();
                    DoDuLieuLenBang();
                }
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Bai_2.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Bai_2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        txtMaSp.setText("");
        txtMaSp.setEditable(true);
        txtTenSp.setText("");
        txtSoLuong.setText("");
        txtDonGia.setText("");
        cboLoaiSanPham.setSelectedIndex(0);
        btnCapNhat.setEnabled(false);
        btnXoa.setEnabled(false);
        btnStart.setEnabled(true);
        btnBack.setEnabled(false);
        btnNext.setEnabled(false);
        btnEnd.setEnabled(true);
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        btnCapNhat.setEnabled(true);
        btnXoa.setEnabled(true);
        tblBang.setRowSelectionInterval(0, 0);
        DanhSach();
        btnStart.setEnabled(false);
        btnBack.setEnabled(false);
        btnNext.setEnabled(true);
        btnEnd.setEnabled(true);
    }//GEN-LAST:event_btnStartActionPerformed

    private void btnEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEndActionPerformed
        btnCapNhat.setEnabled(true);
        btnXoa.setEnabled(true);
        int soDong = tblBang.getRowCount();
        if (soDong > 0) {
            tblBang.setRowSelectionInterval(soDong - 1, soDong - 1);
            DanhSach();
            btnEnd.setEnabled(false);
            btnNext.setEnabled(false);
            btnStart.setEnabled(true);
            btnBack.setEnabled(true);
        }
    }//GEN-LAST:event_btnEndActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        btnCapNhat.setEnabled(true);
        btnXoa.setEnabled(true);
        int index = tblBang.getSelectedRow();
        if (index < tblBang.getRowCount() - 1) {
            tblBang.setRowSelectionInterval(index + 1, index + 1);
            DanhSach();
            btnStart.setEnabled(true);
            btnBack.setEnabled(true);
        }
        if (index == tblBang.getRowCount() - 1) {
            btnNext.setEnabled(false);
            btnEnd.setEnabled(false);
        }
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        btnCapNhat.setEnabled(true);
        btnXoa.setEnabled(true);
        int index = tblBang.getSelectedRow();

        if (index > 0) {
            tblBang.setRowSelectionInterval(index - 1, index - 1);
            DanhSach();
            btnEnd.setEnabled(true);
            btnNext.setEnabled(true);
        } else if (index == 0) {
            tblBang.setRowSelectionInterval(0, 0);
            btnStart.setEnabled(false);
            btnBack.setEnabled(false);

        } else {
            tblBang.setRowSelectionInterval(tblBang.getRowCount() - 1, tblBang.getRowCount() - 1);
            DanhSach();
            btnEnd.setEnabled(true);
            btnNext.setEnabled(true);
        }
    }//GEN-LAST:event_btnBackActionPerformed

    public void DatTenCot() {
        model.addColumn("Mã Sản Phẩm");
        model.addColumn("Tên Sản Phẩm");
        model.addColumn("Loại Sản Phẩm");

        tblBang.setModel(model);
    }

    public boolean check() {
        String mauMaSp = "[a-zA-Z0-9]{1,5}";
        String mauDonGia = "[0-9]{1,50}";
        String mauSoLuong = "[0-9]{1,11}";
        if (txtMaSp.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập Mã Sản Phẩm");
            return false;
        }
        if (!txtMaSp.getText().matches(mauMaSp)) {
            JOptionPane.showMessageDialog(this, "Mã Sản Phẩm Không Hợp Lệ");
            txtMaSp.requestFocus();
            return false;
        }
        if (txtTenSp.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập Tên Sản Phẩm");
            return false;
        }
        if (txtDonGia.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập Đơn Giá");
            return false;
        }
        if (!txtDonGia.getText().matches(mauDonGia)) {
            JOptionPane.showMessageDialog(this, "Đơn Giá phải là số");
            txtDonGia.requestFocus();
            return false;
        }
        if (txtSoLuong.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập Số Lượng");
            return false;
        }
        if (!txtSoLuong.getText().matches(mauSoLuong)) {
            JOptionPane.showMessageDialog(this, "Số Lượng phải là số");
            txtSoLuong.requestFocus();
            return false;
        }
        return true;
    }

    public void KetNoiCSDL() throws ClassNotFoundException, SQLException {
        Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
        String url = "jdbc:sqlserver://localhost:1433; databaseName = QL_BANHANG";
        String user = "sa";
        String pass = "123456";
        ketNoi = DriverManager.getConnection(url, user, pass);
    }

    public void DoDuLieuLenBang() throws ClassNotFoundException, SQLException {
        model.setRowCount(0);
        KetNoiCSDL();
        String sql = "SELECT maSanPham,tenSp,TENLOAI FROM SanPham SP JOIN LOAISANPHAM L ON SP.MALOAI = L.MALOAI";
        PreparedStatement cauLenh = ketNoi.prepareStatement(sql);
        ResultSet ketQua = cauLenh.executeQuery();
        while (ketQua.next() == true) {
            String maSP = ketQua.getString(1);
            String tenSP = ketQua.getString(2);
            String tenLoai = ketQua.getString(3);

            model.addRow(new Object[]{maSP, tenSP, tenLoai});
        }
        ketNoi.close();
    }

    public void DoDuLieuLenComboBox() throws ClassNotFoundException, SQLException {
        KetNoiCSDL();
        String sql = "SELECT TENLOAI FROM LOAISANPHAM";
        PreparedStatement cauLenh = ketNoi.prepareStatement(sql);
        ResultSet ketQua = cauLenh.executeQuery();
        while (ketQua.next() == true) {
            String tenLoai = ketQua.getString(1);
            model_box.addElement(tenLoai);
        }
        cboLoaiSanPham.setModel(model_box);
        ketNoi.close();
    }

    public void DanhSach() {
        int viTri = tblBang.getSelectedRow();
        DecimalFormat df = new DecimalFormat("###,###");
        txtMaSp.setText(tblBang.getValueAt(viTri, 0).toString());
        txtMaSp.setEditable(false);
        txtTenSp.setText(tblBang.getValueAt(viTri, 1).toString());
        cboLoaiSanPham.setSelectedItem(tblBang.getValueAt(viTri, 2).toString());

        try {
            KetNoiCSDL();
            String sql = "SELECT donGia, soLuong FROM SanPham WHERE maSanPham = ?";
            PreparedStatement cauLenh = ketNoi.prepareStatement(sql);
            cauLenh.setString(1, tblBang.getValueAt(viTri, 0).toString());
            ResultSet ketQua = cauLenh.executeQuery();

            while (ketQua.next() == true) {
                txtDonGia.setText(df.format(ketQua.getFloat(1)));
                txtSoLuong.setText(ketQua.getInt(2) + "");
            }
            ketNoi.close();

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Lab_5.Bai_2.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Lab_5.Bai_2.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bai_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bai_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bai_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bai_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Bai_2().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Bai_2.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(Bai_2.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnEnd;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnStart;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboLoaiSanPham;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBang;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtMaSp;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTenSp;
    // End of variables declaration//GEN-END:variables
}
