/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Lab_2;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.xml.bind.annotation.XmlElement;
import sun.text.CompactByteArray;

/**
 *
 * @author ToanNM_PC09504
 */
public class Bai_1_2_3 extends javax.swing.JFrame {

    List<Student> list = new ArrayList<>();

    /**
     * Creates new form Bai_1
     */
    public Bai_1_2_3() {
        initComponents();
        setLocationRelativeTo(null);
        btnXoa.setEnabled(false);
        btnCapNhat.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtHoVaTen = new javax.swing.JTextField();
        txtDiem = new javax.swing.JTextField();
        txtXepLoai = new javax.swing.JTextField();
        cboKhoaHoc = new javax.swing.JComboBox<>();
        chkPT = new javax.swing.JCheckBox();
        btnThem = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnNhapMoi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDanhSach = new javax.swing.JTable();
        btnSapXepTheoDiem = new javax.swing.JButton();
        btnSapXepTheoTen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUẢN LÝ HỌC VIÊN");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("QUẢN LÝ HỌC VIÊN");

        jLabel2.setText("HỌ VÀ TÊN");

        jLabel3.setText("ĐIỂM");

        jLabel4.setText("KHOÁ HỌC");

        jLabel5.setText("XẾP LOẠI");

        txtXepLoai.setEditable(false);

        cboKhoaHoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LẬP TRÌNH JAVA CƠ BẢN", "QUẢN TRỊ CƠ SỞ DỮ LIỆU", "CHÍNH TRỊ", "VÕ VOVINAM", "PHÁP LUẬT" }));

        chkPT.setText("Có phần thưởng?");

        btnThem.setText("THÊM");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnCapNhat.setText("CẬP NHẬT");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnXoa.setText("XOÁ");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnNhapMoi.setText("NHẬP MỚI");
        btnNhapMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapMoiActionPerformed(evt);
            }
        });

        tblDanhSach.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        tblDanhSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "HỌ VÀ TÊN", "ĐIỂM", "KHOÁ HỌC", "XẾP LOẠI", "THƯỞNG"
            }
        ));
        tblDanhSach.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblDanhSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDanhSachMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDanhSach);
        tblDanhSach.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        btnSapXepTheoDiem.setText("Sắp Xếp Theo Điểm");
        btnSapXepTheoDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSapXepTheoDiemActionPerformed(evt);
            }
        });

        btnSapXepTheoTen.setText("Sắp Xếp Theo Tên");
        btnSapXepTheoTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSapXepTheoTenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkPT)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtHoVaTen)
                                .addComponent(txtDiem)
                                .addComponent(txtXepLoai)
                                .addComponent(cboKhoaHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnThem)
                                .addGap(18, 18, 18)
                                .addComponent(btnCapNhat)
                                .addGap(18, 18, 18)
                                .addComponent(btnXoa)
                                .addGap(18, 18, 18)
                                .addComponent(btnNhapMoi))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(btnSapXepTheoDiem)
                        .addGap(31, 31, 31)
                        .addComponent(btnSapXepTheoTen)))
                .addContainerGap(159, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtHoVaTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cboKhoaHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtXepLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(chkPT)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnCapNhat)
                    .addComponent(btnXoa)
                    .addComponent(btnNhapMoi))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSapXepTheoTen)
                    .addComponent(btnSapXepTheoDiem))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public boolean check() {
        //String mauHoTen = "[^0-9]{5,50}";
        String regex = "^[\\p{L}]+(?: [\\p{L}]+)*$";

        if (txtHoVaTen.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên");
            txtHoVaTen.setBackground(Color.yellow);
            txtDiem.setBackground(getBackground());
            txtHoVaTen.requestFocus();
            return false;
        }
        if (!txtHoVaTen.getText().matches(regex)) {
            JOptionPane.showMessageDialog(this, "Họ Tên Không Đúng Định Dạng");
            txtHoVaTen.setBackground(Color.yellow);
            txtDiem.setBackground(getBackground());
            txtHoVaTen.requestFocus();
            return false;
        }
        try {
            txtHoVaTen.setBackground(getBackground());
            if (txtDiem.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "vui lòng nhập điểm");
                txtDiem.setBackground(Color.yellow);
                txtDiem.requestFocus();
                return false;
            }
            if (Double.parseDouble(txtDiem.getText()) < 0 || Double.parseDouble(txtDiem.getText()) > 10) {
                JOptionPane.showMessageDialog(this, "Điểm phải từ (0-10)");
                txtDiem.setBackground(Color.yellow);
                txtDiem.setText("");
                txtDiem.requestFocus();
                return false;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số vào ô điểm");
            txtDiem.requestFocus();
            txtDiem.setBackground(Color.yellow);
            txtDiem.setText("");
            return false;
        }
        txtHoVaTen.setBackground(getBackground());
        txtDiem.setBackground(getBackground());
        return true;
    }

    public void addStudent() {
        if (check()) {
            Student sv = new Student();
            sv.setName(txtHoVaTen.getText());
            sv.setMark(Double.parseDouble(txtDiem.getText()));
            sv.setCourse((String) cboKhoaHoc.getSelectedItem());
            list.add(sv);
            txtXepLoai.setText(sv.getGrade());
            chkPT.setSelected(sv.isBonus());
        }
    }

    public void removeStudent() {
        list.remove(tblDanhSach.getSelectedRow());
        btnXoa.setEnabled(false);
        btnCapNhat.setEnabled(false);
    }

    public void updateStudent() {
        int index = tblDanhSach.getSelectedRow();

        Student st = list.get(index);
        st.setName(txtHoVaTen.getText());
        st.setMark(Double.parseDouble(txtDiem.getText()));
        st.setCourse(cboKhoaHoc.getSelectedItem().toString());
        txtXepLoai.setText(st.getGrade());
        chkPT.setSelected(st.isBonus());
        btnCapNhat.setEnabled(false);
        btnXoa.setEnabled(false);
    }

    public void fillToTable() {
        String[] headers = {"HỌ VÀ TÊN", "ĐIỂM", "KHOÁ HỌC", "XẾP LOẠI", "THƯỞNG"};
        DefaultTableModel model = new DefaultTableModel(headers, 0);
        for (Student st : list) {
            Object[] row = new Object[]{st.getName(), st.getMark(), st.getCourse(), st.getGrade(), st.isBonus() ? "Thưởng" : "Không"};
            model.addRow(row);
        }
        tblDanhSach.setModel(model);
    }

    public void showDetail() {
        int index = tblDanhSach.getSelectedRow();
        Student st = list.get(index);

        txtHoVaTen.setText(st.getName());
        txtDiem.setText(String.valueOf(st.getMark()));
        txtXepLoai.setText(st.getGrade());
        cboKhoaHoc.setSelectedItem(st.getCourse());
        chkPT.setSelected(st.isBonus());
    }

    public void orderByName() {
        Comparator<Student> comp = new Comparator<Student>() {
            @Override
            public int compare(Student st1, Student st2) {
                return st1.getName().compareTo(st2.getName()); //To change body of generated methods, choose Tools | Templates.
            }
        };
        Collections.sort(list, comp);
    }

    public void orderByMarks() {
        Comparator<Student> comp = new Comparator<Student>() {
            @Override
            public int compare(Student d1, Student d2) {
                Double diem1 = d1.getMark();
                Double diem2 = d2.getMark();
                return diem1.compareTo(diem2); //To change body of generated methods, choose Tools | Templates.
            }
        };
        Collections.sort(list, comp.reversed());
    }

    private void btnNhapMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapMoiActionPerformed
        txtHoVaTen.setText("");
        txtDiem.setText("");
        txtXepLoai.setText("");
        cboKhoaHoc.setSelectedIndex(0);
        chkPT.setSelected(false);
        txtHoVaTen.requestFocus();
        txtHoVaTen.setBackground(getBackground());
        txtDiem.setBackground(getBackground());
    }//GEN-LAST:event_btnNhapMoiActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        this.addStudent();
        this.fillToTable();
    }//GEN-LAST:event_btnThemActionPerformed

    private void tblDanhSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhSachMouseClicked
        this.showDetail();
        btnXoa.setEnabled(true);
        btnCapNhat.setEnabled(true);
    }//GEN-LAST:event_tblDanhSachMouseClicked

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int ret = JOptionPane.showConfirmDialog(this, "Bạn muốn xoá không", "Thông Báo", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (ret == JOptionPane.YES_OPTION) {
            this.removeStudent();
            this.fillToTable();
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        if (check()) {
            this.updateStudent();
            this.fillToTable();
        }
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnSapXepTheoDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSapXepTheoDiemActionPerformed
        this.orderByMarks();
        this.fillToTable();
    }//GEN-LAST:event_btnSapXepTheoDiemActionPerformed

    private void btnSapXepTheoTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSapXepTheoTenActionPerformed
        this.orderByName();
        this.fillToTable();
    }//GEN-LAST:event_btnSapXepTheoTenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bai_1_2_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bai_1_2_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bai_1_2_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bai_1_2_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bai_1_2_3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnNhapMoi;
    private javax.swing.JButton btnSapXepTheoDiem;
    private javax.swing.JButton btnSapXepTheoTen;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboKhoaHoc;
    private javax.swing.JCheckBox chkPT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDanhSach;
    private javax.swing.JTextField txtDiem;
    private javax.swing.JTextField txtHoVaTen;
    private javax.swing.JTextField txtXepLoai;
    // End of variables declaration//GEN-END:variables
}
