/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Lab_7;

import java.io.IOException;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextPane;

/**
 *
 * @author ToanNM_PC09504
 */
public class Chat_Server extends javax.swing.JFrame {
    Chat_Message_Socket mSocket;
    /**
     * Creates new form Chat_Server
     */
    public Chat_Server() {
        initComponents();
        pnlBieuCam.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtPort = new javax.swing.JTextField();
        btnStart = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txpMessage = new javax.swing.JTextArea();
        txtMessage = new javax.swing.JTextField();
        btnSend = new javax.swing.JButton();
        btnBieuCam = new javax.swing.JToggleButton();
        pnlBieuCam = new javax.swing.JPanel();
        lblCuoi = new javax.swing.JLabel();
        lblNgang = new javax.swing.JLabel();
        lblBuon = new javax.swing.JLabel();
        lblChao = new javax.swing.JLabel();
        lblLike = new javax.swing.JLabel();
        lblOk = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Server");

        jLabel1.setText("Port No.");

        txtPort.setText("9998");

        btnStart.setText("Start");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        jLabel2.setText("Client Say");

        txpMessage.setColumns(20);
        txpMessage.setRows(5);
        jScrollPane1.setViewportView(txpMessage);

        btnSend.setText("Send");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });

        btnBieuCam.setFont(new java.awt.Font("Wingdings", 0, 14)); // NOI18N
        btnBieuCam.setText("");
        btnBieuCam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBieuCamActionPerformed(evt);
            }
        });

        pnlBieuCam.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlBieuCam.setLayout(new java.awt.GridLayout());

        lblCuoi.setFont(new java.awt.Font("Wingdings", 0, 24)); // NOI18N
        lblCuoi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCuoi.setText("");
        lblCuoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCuoiMouseClicked(evt);
            }
        });
        pnlBieuCam.add(lblCuoi);

        lblNgang.setFont(new java.awt.Font("Wingdings", 0, 24)); // NOI18N
        lblNgang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNgang.setText("");
        lblNgang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNgangMouseClicked(evt);
            }
        });
        pnlBieuCam.add(lblNgang);

        lblBuon.setFont(new java.awt.Font("Wingdings", 0, 24)); // NOI18N
        lblBuon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBuon.setText("");
        lblBuon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBuonMouseClicked(evt);
            }
        });
        pnlBieuCam.add(lblBuon);

        lblChao.setFont(new java.awt.Font("Wingdings", 0, 24)); // NOI18N
        lblChao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblChao.setText("");
        lblChao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblChaoMouseClicked(evt);
            }
        });
        pnlBieuCam.add(lblChao);

        lblLike.setFont(new java.awt.Font("Wingdings", 0, 24)); // NOI18N
        lblLike.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLike.setText("");
        lblLike.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLikeMouseClicked(evt);
            }
        });
        pnlBieuCam.add(lblLike);

        lblOk.setFont(new java.awt.Font("Wingdings", 0, 24)); // NOI18N
        lblOk.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOk.setText("");
        lblOk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOkMouseClicked(evt);
            }
        });
        pnlBieuCam.add(lblOk);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("SERVER");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlBieuCam, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtPort, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(26, 26, 26)
                                    .addComponent(btnStart))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnBieuCam, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnSend, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStart))
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMessage)
                    .addComponent(btnSend, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBieuCam, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlBieuCam, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        try {
            int port = Integer.parseInt(txtPort.getText());
            ServerSocket serverSocket = new ServerSocket(port);
            Thread t = new Thread()
            {
                public void run()
                {
                    try {
                        txpMessage.setText("Đang chờ đợi kết nối.........");
                        Socket socket = serverSocket.accept();
                        txpMessage.setText(txpMessage.getText()+"\nCó Client đang kết nối.........");
                        mSocket = new Chat_Message_Socket(socket, txpMessage);
                    } catch (IOException ex) {
                        
                    }
                    
                }
            };
            t.start();
        } catch (IOException ex) {
            Logger.getLogger(Chat_Server.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnStartActionPerformed

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        if(txtMessage.getText().equals(""))
           return;
       else
       {
           mSocket.send(txtMessage.getText());
           txtMessage.setText("");
           txtMessage.requestFocus();
       }
    }//GEN-LAST:event_btnSendActionPerformed

    private void btnBieuCamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBieuCamActionPerformed
        if(btnBieuCam.isSelected()==true){
            pnlBieuCam.setVisible(true);
        }else
            pnlBieuCam.setVisible(false);
    }//GEN-LAST:event_btnBieuCamActionPerformed

    private void lblCuoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCuoiMouseClicked
        txtMessage.setText(txtMessage.getText()+"");
    }//GEN-LAST:event_lblCuoiMouseClicked

    private void lblNgangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNgangMouseClicked
        txtMessage.setText(txtMessage.getText()+"");
    }//GEN-LAST:event_lblNgangMouseClicked

    private void lblBuonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBuonMouseClicked
        txtMessage.setText(txtMessage.getText()+"");
    }//GEN-LAST:event_lblBuonMouseClicked

    private void lblChaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblChaoMouseClicked
        txtMessage.setText(txtMessage.getText()+"");
    }//GEN-LAST:event_lblChaoMouseClicked

    private void lblLikeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLikeMouseClicked
        txtMessage.setText(txtMessage.getText()+"");
    }//GEN-LAST:event_lblLikeMouseClicked

    private void lblOkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOkMouseClicked
        txtMessage.setText(txtMessage.getText()+"");
    }//GEN-LAST:event_lblOkMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Chat_Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Chat_Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Chat_Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Chat_Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Chat_Server().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnBieuCam;
    private javax.swing.JButton btnSend;
    private javax.swing.JButton btnStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBuon;
    private javax.swing.JLabel lblChao;
    private javax.swing.JLabel lblCuoi;
    private javax.swing.JLabel lblLike;
    private javax.swing.JLabel lblNgang;
    private javax.swing.JLabel lblOk;
    private javax.swing.JPanel pnlBieuCam;
    private javax.swing.JTextArea txpMessage;
    private javax.swing.JTextField txtMessage;
    private javax.swing.JTextField txtPort;
    // End of variables declaration//GEN-END:variables

    
}
